### ISSUE TITLE
How do I place attributes?:sparkles: 

### ISSUE THREAD

**Issue by taozina0587** [Zuoqiu-Yingyi/siyuan-theme-dark-plus#171]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

Hello. Sorry to ask a question here, but I don't know of another way. I'm a newbie with SiYuan and I live in Brazil. So I don't know your native language very well. How do I add these functions to a table? I use tables a lot for my studies. Thanks

![image](https://user-images.githubusercontent.com/90691302/208633273-929abe73-d629-4f61-9839-bcd050f82552.png)

### 描述可能的最优解决方案 Describe the optimal solution

thanks

**Comment by Zuoqiu-Yingyi** [comment]
I'm sorry to tell you that these features can only be applied to the entire table, not to a certain cell.

This is because the minimum granularity of a style is a block, such as _table block_.

The table simply from [writing-mode - CSS: Cascading Style Sheets | MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/writing-mode) **just** for showing what the style should look like when attribute `writing-mode` is set to a different value.

**Comment by taozina0587** [comment]
Got it, buddy. But where, in SiYuan, do I add the attribute and value as you explain? I'm looking for it, but I can't find it in the program.

**Comment by Zuoqiu-Yingyi** [comment]
> Got it, buddy (巴迪) . But where, in SiYuan, do I add the attribute and value as you explain (解释) ? I'm looking for it, but I can't find it in the program.
> Here? What is "key"?

`key`: Custom attribute Name
`value`: Custom attribute Value

You can also use `Block Menu Enhancements` function to use the context menu to set these custom attributes.
